#!/bin/sh
#SBATCH --job-name=FastcarResults
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=FastcarResults.logfile
#SBATCH --time=01:00:00

#Opening correct folder
cd $VSC_SCRATCH/lise/17_Baproeven/Killian/FASTCAR/BOLTCAR

#Defining Gaussian Parameters
export PATH=/vscmnt/brussel_pixiu_home/_user_brussel/105/vsc10536/bin/:$PATH

#Loading modules
module load openpyxl/3.1.2-GCCcore-12.3.0

#Launching calculation
cp Automated_Reagents.py ./CREST/TS-CREST/Automated_Reagents.py
cd CREST/
cd TS-CREST/
chmod 777 Automated_Reagents.py
python Automated_Reagents.py
